# SPDX-FileCopyrightText: 2024 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Mississippi"
SPDX-PackageSupplier = "Arnaldo Cesco <arnaldo.cesco@secomind.com>"
SPDX-PackageDownloadLocation = "https://github.com/secomind/mississippi"
annotations = []
